spring.config.import=optional:file:.env[.properties]

spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Admin Credentials (Spring Security Defaults)
spring.security.user.name=${ADMIN_USER}
spring.security.user.password=${ADMIN_PASS}
spring.security.user.roles=ADMIN

# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.from=${MAIL_USERNAME}

# Configurable Notification Retention Period (in days)
notification.retention.days=30

# Configurable Frontend Client URL for reset password links
app.client.url=${APP_CLIENT_URL:http://wbs.oryfolks.com}

# OTP Verification & Limits
otp.expiry.minutes=15
otp.max.attempts=5
otp.max.resends=3
